### ISSUE TITLE
Bases de datos para los módulos

### ISSUE THREAD

**Issue by joaquinceballos** [Arquisoft/Inci_e1a#2]
Creadas dos bases de datos MySQL para los módulos. Cada una está en una máquina distinta.
<table>
<tr>
<th>Módulos</th>
<th>ip:puerto</th>
<th>Base de Datos</th>
<th>Usuario/password</th>
</tr>
<tr>
<td>Loader/Agent</td>
<td>54.190.197.178:3306</td>
<td>agent</td>
<td>agent/respeto</td>
</tr>
<tr>
<td>InciManager/InciDashboard</td>
<td>34.210.218.163:3306</td>
<td>inci</td>
<td>inci/respeto</td>
</tr>
</table>

Se ha probado a conectar y ok pero está pendiente cambiar el código para que tiren de ellas.

**Comment by joaquinceballos** [comment]
Tengo problemas para cambiar el módulo de Loader para usar la base de datos nueva.

No entiendo bien el proyecto, si podéis mirarlo los del grupo e1a1.

En principio nada más sería necesario cambiar la dependencia en el pom.xml y añadir los parámetros de conexión a la base de datos en el properties:

- spring.datasource.url=jdbc:mysql://54.190.197.178:3306/agent?useSSL=false
- spring.datasource.username=agent
- spring.datasource.password=respeto

He visto que se añade la librería HSQLDB al path manualmente, pero aunque lo quité seguía por algún sitio dango guerra.

**Comment by cesaralvarez97** [comment]
El Loader ya se conecta a la base de datos, también se ha refactorizado el código para que coincidan ambas(Fernando refactorizó).
